<a href="https://colab.research.google.com/github/nareshyadav2912/fakenewsdetection/blob/main/Fake_News_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the Libraries

In [ ]:
import numpy as np
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

In [ ]:
import nltk
nltk.download('stopwords')

In [ ]:
print(stopwords.words('english'))

In [ ]:
dataset = pd.read_csv("train.csv")
dataset.head(10)

In [ ]:
dataset.shape

In [ ]:
dataset.isnull().sum()

In [ ]:
dataset1=dataset.fillna("")
dataset1.isnull().sum()

In [ ]:
dataset1['content']=dataset1['author']+' '+dataset1['title']
dataset1['content'].head()

In [ ]:
X=dataset1.drop('label',axis=1)
Y=dataset1['label']
#Y.head()
X.head()

In [ ]:
X.shape,Y.shape

In [ ]:
ps=PorterStemmer()

In [ ]:
def stemming(content):
  stemmed_content = re.sub('[^a-zA-Z]', ' ', content)
  # sub substitues some values, numbers and space will be substituted by space in content
  # it is a regular expression syntax
  stemmed_content = stemmed_content.lower()
  # makes words to lowercase
  stemmed_content = stemmed_content.split()
  # splits the content 
  stemmed_content = [ps.stem(word) for word in stemmed_content if not word in stopwords.words('english')]
  stemmed_content = ' '.join(stemmed_content)
  return stemmed_content

In [ ]:
dataset1['content']=dataset1['content'].apply(stemming)
dataset1['content']

In [ ]:
X=dataset1['content'].values
Y=dataset1['label'].values

In [ ]:
print(X)

In [ ]:
print(Y)

In [ ]:
vector=TfidfVectorizer()
vector.fit(X)
X=vector.transform(X)

In [ ]:
print(X)

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, stratify = Y, random_state =2)

In [ ]:
lr=LogisticRegression()
lr.fit(X_train,Y_train)

LogisticRegression()

In [ ]:
X_train_pred = lr.predict(X_train)
td_ac = accuracy_score(X_train_pred, Y_train )

In [136]:
print(" Accuracy score for the traing data : ",td_ac*100)

 Accuracy score for the traing data :  99.93990384615384


In [137]:
X_test_pred = lr.predict(X_test)
td_ac = accuracy_score(X_test_pred, Y_test )

In [138]:
print(" Accuracy score for the testing data : ",td_ac*100)

 Accuracy score for the testing data :  97.90865384615385


In [ ]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Y_test, X_test_pred))

[[2004   73]
 [  14 2069]]


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,X_test_pred))

              precision    recall  f1-score   support

           0       0.99      0.96      0.98      2077
           1       0.97      0.99      0.98      2083

    accuracy                           0.98      4160
   macro avg       0.98      0.98      0.98      4160
weighted avg       0.98      0.98      0.98      4160



In [126]:
from sklearn.svm import LinearSVC

In [128]:
sv=LinearSVC()
sv.fit(X_train,Y_train)

LinearSVC()

In [129]:
X_train_pred = sv.predict(X_train)
td_ac = accuracy_score(X_train_pred, Y_train)

In [135]:
print(" Accuracy score for the traing data : ",td_ac*100)

 Accuracy score for the traing data :  99.93990384615384


In [ ]:
X_test_pred = sv.predict(X_test)
td_ac = accuracy_score(X_test_pred, Y_test )

In [134]:
print(" Accuracy score for the testing data : ",td_ac*100)

 Accuracy score for the testing data :  99.93990384615384


In [132]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Y_test, X_test_pred))

[[2004   73]
 [  14 2069]]


In [133]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,X_test_pred))

              precision    recall  f1-score   support

           0       0.99      0.96      0.98      2077
           1       0.97      0.99      0.98      2083

    accuracy                           0.98      4160
   macro avg       0.98      0.98      0.98      4160
weighted avg       0.98      0.98      0.98      4160



In [139]:
from sklearn.naive_bayes import MultinomialNB

In [141]:
nv=MultinomialNB()
nv.fit(X_train,Y_train)

MultinomialNB()

In [143]:
X_train_pred = nv.predict(X_train)
td_ac = accuracy_score(X_train_pred, Y_train)

In [144]:
print(" Accuracy score for the traing data : ",td_ac*100)

 Accuracy score for the traing data :  97.82451923076924


In [145]:
X_test_pred = nv.predict(X_test)
td_ac = accuracy_score(X_test_pred, Y_test )

In [146]:
print(" Accuracy score for the testing data : ",td_ac*100)

 Accuracy score for the testing data :  95.5048076923077


In [147]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Y_test, X_test_pred))

[[2064   13]
 [ 174 1909]]


In [148]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,X_test_pred))

              precision    recall  f1-score   support

           0       0.92      0.99      0.96      2077
           1       0.99      0.92      0.95      2083

    accuracy                           0.96      4160
   macro avg       0.96      0.96      0.95      4160
weighted avg       0.96      0.96      0.95      4160

